Added description of data
UBC-MDS/DSCI-532_2024_10_vanweather pull request #13
Opened 2024-03-27 05:11 UTC by sivakornchong

Explained clearly the data used here.

2024-03-28 17:09 UTC, WeilinHan8 requested changes

2024-03-28 17:09 UTC, WeilinHan8 commented on reports/m1_proposal.md
> +- Overall weather: "weather_code"
I think you would borrow some description of variable from the webesite, such as, weather code: _Weather condition as a numeric code. Follow WMO weather interpretation codes. See table below for details. Weather code is calculated from cloud cover analysis, precipitation, snowfall, cape and gusts._ I think we need to give some variables examples.

2024-03-30 00:14 UTC, AnuBanga approved these changes
Review completed

2024-03-30 02:00 UTC, WeilinHan8 approved these changes
Looks good! Thank you!

2024-03-30 02:00 UTC, merged